nodeLinker: pnp

packageExtensions:
  "@mdx-js/react@*":
    peerDependencies:
      "@types/react": "*"
  "@radix-ui/react-dialog@*":
    peerDependencies:
      "@types/react": "*"
  "@radix-ui/react-slot@*":
    peerDependencies:
      "@types/react": "*"
  next-mdx-remote@*:
    peerDependencies:
      "@types/react": "*"
      react: "*"
      react-dom: "*"
  next@*:
    dependencies:
      styled-jsx: "*"
    peerDependencies:
      "@opentelemetry/api": "*"
      "@types/react": "*"
      "@types/react-dom": "*"
      react: "*"
      react-dom: "*"
      typescript: "*"

pnpEnableEsmLoader: true

pnpMode: loose
